### PR TITLE
Typescript Typings

### PR DESCRIPTION
**Pull request by shilangyu**

### CODE REVIEW

**Comment by MatejBransky** [comment]
Thanks a lot! 👍

**Comment by shilangyu** [comment]
Looks like I accidentally removed newline at the end of README and d.ts file, sorry for that

**Comment by MatejBransky** [comment]
Who cares? :) I'm glad for your typings.

**Comment by mariusGundersen** [comment]
It doesn't seem like this has been published to npm yet? It would be nice to have the typescript typings, so can you publish a new version with this merged pull-request?

**Pull request merged**
